kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb
  namespace: "default"
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/component: mongodb
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"
