kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-persistent-storage
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: persistent-volume-claim
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"
