apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-sa
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis
    app.kubernetes.io/component: database
secrets:
  - name: redis-secret
automountServiceAccountToken: true
