---
# Source: mysql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: "default"
  labels:
    app.kubernetes.io/name: mysql
    helm.sh/chart: mysql-9.4.8
    app.kubernetes.io/instance: mysql
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  mysql-root-password: "bkhjRzFwVUhtNw=="
  mysql-password: "WDNxNDJXNWVzeg=="
