---
# Source: redis/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: redis
  namespace: "default"
  labels:
    app.kubernetes.io/name: redis
    helm.sh/chart: redis-17.7.1
    app.kubernetes.io/instance: redis
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  redis-password: "U04wSk5ZRGI3Yw=="
