apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  namespace: "default"
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/instance: rabbitmq
type: Opaque
data:
  rabbitmq-password: "YWRtaW4="

  rabbitmq-erlang-cookie: "SHRmdFZtVlF1ZzhCNVN1MG9ZUW1FUm1COGUxNHhnSUc="
