apiVersion: v1
kind: ServiceAccount
metadata:
  name: rabbitmq-sa
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: service-account
automountServiceAccountToken: true
secrets:
  - name: rabbitmq
