apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/component: database
type: Opaque
data:
  mongodb-root-password: "cm9vdA=="
