apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: secret
type: Opaque
data:
  mysql-root-password: "cm9vdA=="
