---
# Source: rabbitmq/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  namespace: "default"
  labels:
    app.kubernetes.io/name: rabbitmq
    helm.sh/chart: rabbitmq-11.9.0
    app.kubernetes.io/instance: rabbitmq
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  rabbitmq-password: "UEVUMnluRzBDNUZBV0daWg=="
  
  rabbitmq-erlang-cookie: "SHRmdFZtVlF1ZzhCNVN1MG9ZUW1FUm1COGUxNHhnSUc="
