apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: "default"
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: mysql
type: Opaque
data:
  mysql-root-password: "cm9vdA=="
