apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql
  namespace: "default"
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: mysql
  annotations:
    description: "Service account for the MySQL database service"
automountServiceAccountToken: true
secrets:
  - name: mysql
